version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"

  # CMake dependencies (if using FetchContent or similar)
  - package-ecosystem: "cmake"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3