set(CTEST_PROJECT_NAME "HDF5 VOL Tests")
set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

set(CTEST_DROP_METHOD "https")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=HDF5%20VOL%20Tests")
set(CTEST_DROP_SITE_CDASH TRUE)
